# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alone_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1269, 228)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.clbRefresh = QtWidgets.QCommandLinkButton(self.frame_8)
        self.clbRefresh.setMaximumSize(QtCore.QSize(33, 16777215))
        self.clbRefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clbRefresh.setIcon(icon)
        self.clbRefresh.setDescription("")
        self.clbRefresh.setObjectName("clbRefresh")
        self.horizontalLayout_10.addWidget(self.clbRefresh)
        self.calBirtday = QtWidgets.QDateEdit(self.frame_8)
        self.calBirtday.setAccessibleDescription("")
        self.calBirtday.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.calBirtday.setCalendarPopup(True)
        self.calBirtday.setDate(QtCore.QDate(1901, 1, 1))
        self.calBirtday.setObjectName("calBirtday")
        self.horizontalLayout_10.addWidget(self.calBirtday)
        self.pbSortF = QtWidgets.QPushButton(self.frame_8)
        self.pbSortF.setObjectName("pbSortF")
        self.horizontalLayout_10.addWidget(self.pbSortF)
        self.pbSortIO = QtWidgets.QPushButton(self.frame_8)
        self.pbSortIO.setObjectName("pbSortIO")
        self.horizontalLayout_10.addWidget(self.pbSortIO)
        self.pbSortO = QtWidgets.QPushButton(self.frame_8)
        self.pbSortO.setObjectName("pbSortO")
        self.horizontalLayout_10.addWidget(self.pbSortO)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.clbRefreshReport = QtWidgets.QCommandLinkButton(self.frame_8)
        self.clbRefreshReport.setMaximumSize(QtCore.QSize(33, 16777215))
        self.clbRefreshReport.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clbRefreshReport.setIcon(icon1)
        self.clbRefreshReport.setDescription("")
        self.clbRefreshReport.setObjectName("clbRefreshReport")
        self.horizontalLayout_10.addWidget(self.clbRefreshReport)
        self.clbReport2xlsx = QtWidgets.QCommandLinkButton(self.frame_8)
        self.clbReport2xlsx.setMaximumSize(QtCore.QSize(33, 16777215))
        self.clbReport2xlsx.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("saveXLSX.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clbReport2xlsx.setIcon(icon2)
        self.clbReport2xlsx.setDescription("")
        self.clbReport2xlsx.setObjectName("clbReport2xlsx")
        self.horizontalLayout_10.addWidget(self.clbReport2xlsx)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.cbFolder = QtWidgets.QComboBox(self.frame_8)
        self.cbFolder.setObjectName("cbFolder")
        self.horizontalLayout_10.addWidget(self.cbFolder)
        self.leFile = QtWidgets.QLineEdit(self.frame_8)
        self.leFile.setObjectName("leFile")
        self.horizontalLayout_10.addWidget(self.leFile)
        self.clbSave = QtWidgets.QCommandLinkButton(self.frame_8)
        self.clbSave.setMaximumSize(QtCore.QSize(33, 16777215))
        self.clbSave.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clbSave.setIcon(icon3)
        self.clbSave.setDescription("")
        self.clbSave.setObjectName("clbSave")
        self.horizontalLayout_10.addWidget(self.clbSave)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.twRez = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twRez.sizePolicy().hasHeightForWidth())
        self.twRez.setSizePolicy(sizePolicy)
        self.twRez.setObjectName("twRez")
        self.twRez.setColumnCount(0)
        self.twRez.setRowCount(0)
        self.verticalLayout_6.addWidget(self.twRez)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.calBirtday.setDisplayFormat(_translate("Form", "dd.MM.yyyy"))
        self.pbSortF.setText(_translate("Form", "Фамилия"))
        self.pbSortIO.setText(_translate("Form", "Имя-Отчество"))
        self.pbSortO.setText(_translate("Form", "Отчество"))

